### ISSUE TITLE
Unintuitive paramethers 

### ISSUE THREAD

**Issue by JakubiM** [PureFour/workout-rival#14]
Unintuitive paramethers names in Swagger-UI in endpoint 
**/workoutRival/users/email Update user email**
![Screenshot from 2020-03-01 20-47-29](https://user-images.githubusercontent.com/43807553/75632645-686cc100-5bfe-11ea-8134-fdee96078ee2.png)

**Comment by michaljk1** [comment]
Я не розумію, лише українська
